'use client';

import { createContext, useContext, useState, useEffect, type ReactNode } from 'react';

export type Language = 'tr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('tr');
  const [isInitialized, setIsInitialized] = useState<boolean>(false);

  // Initialize language based on geolocation, then check localStorage
  useEffect(() => {
    const initializeLanguage = async () => {
      if (typeof window !== 'undefined' && window.localStorage) {
        try {
          // First, check if user has manually set a language preference
          const savedLanguage = localStorage.getItem('fitto_language');
          if (savedLanguage === 'tr' || savedLanguage === 'en') {
            setLanguageState(savedLanguage as Language);
            setIsInitialized(true);
            return;
          }

          // If no saved preference, detect based on geolocation
          try {
            const geoResponse = await fetch('/api/geolocation');
            if (geoResponse.ok) {
              const geoData = await geoResponse.json() as { country?: string };
              const detectedLanguage: Language = geoData.country === 'TR' ? 'tr' : 'en';
              setLanguageState(detectedLanguage);
              // Don't save to localStorage yet - let user explicitly change it
            }
          } catch (geoError) {
            console.error('[LanguageContext] Geolocation detection failed:', geoError);
            // Fallback to 'tr' if geolocation fails
          }
        } catch (error) {
          console.error('[LanguageContext] Failed to load language preference:', error);
        }
        setIsInitialized(true);
      }
    };

    initializeLanguage();
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined' && window.localStorage) {
      try {
        localStorage.setItem('fitto_language', lang);
      } catch (error) {
        console.error('[LanguageContext] Failed to save language preference:', error);
      }
    }
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: Record<string, unknown> | string = translations[language];
    
    for (const k of keys) {
      if (value && typeof value === 'object' && k in value) {
        const nextValue = (value as Record<string, unknown>)[k];
        if (typeof nextValue === 'string' || (typeof nextValue === 'object' && nextValue !== null)) {
          value = nextValue as Record<string, unknown> | string;
        } else {
          return key; // Return key if translation not found
        }
      } else {
        return key; // Return key if translation not found
      }
    }
    
    return typeof value === 'string' ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    // ⚠️ FALLBACK: Return safe default instead of throwing error
    // This prevents crashes when LanguageProvider is accidentally missing
    console.warn('[LanguageContext] useLanguage used outside LanguageProvider. Returning fallback.');
    return {
      language: 'tr' as Language,
      setLanguage: () => {
        console.warn('[LanguageContext] setLanguage called outside provider, ignoring.');
      },
      t: (key: string) => key, // Return key as fallback
    };
  }
  return context;
}

// Comprehensive Translations
const translations: Record<Language, Record<string, any>> = {
  tr: {
    // Common
    common: {
      save: 'Kaydet',
      cancel: 'İptal',
      delete: 'Sil',
      edit: 'Düzenle',
      back: 'Geri',
      next: 'Devam Et',
      finish: 'Tamamla',
      skip: 'Atla',
      yes: 'Evet',
      no: 'Hayır',
      loading: 'Yükleniyor...',
      error: 'Hata',
      success: 'Başarılı',
      add: 'Ekle',
      search: 'Ara',
      close: 'Kapat',
      select: 'Seç',
    },
    
    // Welcome Screen
    welcome: {
      title: "Fitto'ya Hoş Geldiniz",
      description: "Sağlıklı yaşam yolculuğunuzda yanınızdayız. Kalori, makro ve egzersiz takibi artık çok kolay!",
      slide1Title: "Fitto'ya Hoş Geldiniz",
      slide1Desc: "Sağlıklı yaşam yolculuğunuzda yanınızdayız. Kalori, makro ve egzersiz takibi artık çok kolay!",
      slide2Title: "Hedeflerinizi Belirleyin",
      slide2Desc: "Kilo vermek, kas yapmak veya sağlıklı kalmak - hedefiniz ne olursa olsun, size özel plan oluşturun.",
      slide3Title: "İlerlemenizi İzleyin",
      slide3Desc: "Günlük kalori, makro besinler, su tüketimi ve daha fazlasını kolayca takip edin.",
      slide4Title: "Sonuçları Görün",
      slide4Desc: "Detaylı raporlar ve grafiklerle ilerlemenizi analiz edin, motivasyonunuzu yüksek tutun!",
      getStarted: "Başlayalım",
      continue: "Devam Et",
    },
    
    // Onboarding
    onboarding: {
      createProfile: "Profilini Oluştur ✨",
      step1Desc: "Kişisel bilgilerinizi girin",
      step2Desc: "Hedeflerinizi belirleyin",
      username: "Kullanıcı Adı",
      usernamePlaceholder: "Adınız",
      age: "Yaş",
      agePlaceholder: "Örn: 25",
      weight: "Kilo (kg)",
      weightPlaceholder: "Örn: 70",
      height: "Boy (cm)",
      heightPlaceholder: "Örn: 175",
      gender: "Cinsiyet",
      genderSelect: "Seçiniz",
      male: "Erkek",
      female: "Kadın",
      other: "Diğer",
      activityLevel: "Aktivite Seviyesi",
      sedentary: "Hareketsiz (Ofis işi)",
      lightlyActive: "Az Aktif (Hafif egzersiz 1-3 gün/hafta)",
      moderatelyActive: "Orta Aktif (Orta egzersiz 3-5 gün/hafta)",
      veryActive: "Çok Aktif (Yoğun egzersiz 6-7 gün/hafta)",
      extraActive: "Ekstra Aktif (Ağır fiziksel iş)",
      goal: "Hedef",
      lose: "Kilo Vermek",
      maintain: "Kilonu Korumak",
      gain: "Kilo Almak",
      buildMuscle: "Kas Yapmak",
      targetWeight: "Hedef Kilo (kg)",
      back: "← Geri",
      complete: "Tamamla ✓",
    },
    
    // Bottom Navigation
    nav: {
      home: "Ana Sayfa",
      stats: "İstatistik",
      recipes: "Tarifler",
      more: "Daha Fazla",
      profile: "Profil",
    },
    
    // Profile
    profile: {
      title: "Profilim",
      description: "Kişisel bilgileriniz ve hedefleriniz",
      currentWeight: "Mevcut Kilo (kg)",
      height: "Boy (cm)",
      bmi: "BMI",
      targetWeight: "Hedef Kilo (kg)",
      myGoals: "Hedeflerim",
      activityLevel: "Aktivite Seviyesi",
      goalType: "Hedef Tipi",
      dailyCalorie: "Günlük Kalori",
      macroGoals: "Günlük Makro Hedeflerim",
      protein: "Protein",
      carbs: "Karbonhidrat",
      fat: "Yağ",
      age: "yaş",
      underweight: "Zayıf",
      normal: "Normal",
      overweight: "Fazla Kilolu",
      obese: "Obez",
    },
    
    // Meal Tracking
    meals: {
      title: "Yemek Takibi",
      description: "Günlük öğünlerinizi kaydedin",
      dailyCalorie: "Günlük Kalori",
      yourGoal: "Bugünkü hedefiniz",
      remaining: "kalan",
      goalReached: "🎉 Günlük hedefinize ulaştınız!",
      completed: "tamamlandı",
      dailyMeals: "Günlük Öğünler",
      breakfast: "Kahvaltı",
      lunch: "Öğle Yemeği",
      dinner: "Akşam Yemeği",
      snack: "Atıştırmalık",
      snackAlt: "Ara Öğün",
      notAdded: "Henüz eklenmedi",
      foods: "yemek",
      motivationStart: "🍽️ İlk öğününüzü eklemeye başlayın!",
      motivationGood: "💪 Harika gidiyorsunuz! Devam edin!",
      motivationClose: "🔥 Hedefinize çok yaklaştınız!",
      motivationComplete: "🎉 Günlük hedefinize ulaştınız!",
      balancedDiet: "Dengeli beslenme sağlıklı yaşamın temelidir",
      addMeal: "Yemek Ekle",
      addMealDesc: "Bugünkü öğününüze besin ekleyin",
      mealType: "Öğün",
      searchFood: "Besin Ara",
      searchPlaceholder: "Örn: tavuk, peynir, elma...",
      recentFoods: "Son Kullanılanlar",
      foundResults: "Bulunan Sonuçlar",
      noResults: "için sonuç bulunamadı",
      noResultsHelp: "Özel gıda ekle seçeneğini kullanabilirsiniz",
      portion: "Porsiyon (gram)",
      nutritionValues: "Besin Değerleri",
      calories: "Kalori",
      addPhoto: "📸 Fotoğraf Ekle",
      customFood: "Özel Gıda",
      barcodeScan: "Barkod Tara",
      minChars: "En az 3 karakter girin...",
    },
    
    // Exercise Tracking
    exercise: {
      title: "Egzersiz Takibi",
      description: "Aktif ve sağlıklı kal! 💪",
      add: "Ekle",
      today: "Bugün",
      stats: "İstatistikler",
      history: "Geçmiş",
      todaySummary: "Bugünün Özeti",
      caloriesBurned: "Yakılan Kalori",
      minutes: "Dakika",
      weeklyGoal: "Haftalık Hedef",
      weeklyGoalDesc: "Haftada 150 dakika egzersiz önerilir 🎯",
      todayExercises: "Bugünün Egzersizleri",
      noExerciseToday: "Henüz bugün egzersiz eklemediniz.",
      letsGetMoving: "Hadi harekete geçelim! 🚀",
      addFirstExercise: "İlk Egzersizini Ekle",
      favoriteExercises: "Favori Egzersizlerim",
      thisWeek: "Bu Hafta",
      thisMonth: "Bu Ay",
      all: "Tümü",
      totalCalories: "Toplam Kalori",
      totalMinutes: "Toplam Dakika",
      exerciseCount: "Egzersiz Sayısı",
      avgPerSession: "Ort. Kalori/Seans",
      mostFrequent: "En Sık Yapılan Egzersiz",
      last7Days: "Son 7 Gün",
      noExerciseHistory: "Henüz egzersiz geçmişiniz yok.",
      startFirst: "İlk egzersize başlamak için yukarıdaki butona tıklayın! 💪",
      tip: "💡 İpucu",
      tipText: "Düzenli egzersiz yaparak metabolizmanızı hızlandırabilir ve daha fazla kalori yakabilirsiniz!",
      addExercise: "Egzersiz Ekle",
      addExerciseDesc: "Bugünkü aktivitenizi kaydedin",
      commonExercises: "Yaygın Egzersizler",
      customExercise: "Özel Egzersiz",
      customExercisePlaceholder: "Kendi egzersizin adını yaz...",
      duration: "Süre (dakika)",
      caloriesBurnedInput: "Yakılan Kalori (kcal)",
      walking: "Yürüyüş",
      running: "Koşu",
      cycling: "Bisiklet",
      swimming: "Yüzme",
      weightTraining: "Ağırlık Çalışması",
      yoga: "Yoga",
      pilates: "Pilates",
      dancing: "Dans",
      exercises: "egzersiz",
    },
    
    // Stats Page
    stats: {
      title: "İstatistiklerim",
      description: "İlerlemenizi takip edin ve hedeflerinize ulaşın!",
      consecutiveDays: "Ardışık Gün",
      mealLogs: "Yemek Kaydı",
      avgCalories: "Ort. Kalori",
      exercises: "Egzersiz",
      weekly: "Haftalık",
      monthly: "Aylık",
      
      // Achievements
      achievements: "Başarılar",
      firstStep: "İlk Adım",
      firstStepDesc: "İlk yemeğini kaydet",
      determined: "Kararlı",
      determinedDesc: "7 gün üst üste kayıt yap",
      disciplined: "Disiplinli",
      disciplinedDesc: "30 gün üst üste kayıt yap",
      follower: "Takipçi",
      followerDesc: "50 yemek kaydet",
      expert: "Uzman",
      expertDesc: "100 yemek kaydet",
      active: "Aktif",
      activeDesc: "10 egzersiz kaydet",
      athlete: "Sporcu",
      athleteDesc: "50 egzersiz kaydet",
      superHero: "Süper Kahraman",
      superHeroDesc: "100 yemek + 50 egzersiz",
      allUnlocked: "🎉 Tüm Başarıları Kazandınız!",
      greatJob: "Harika bir iş çıkardınız!",
      
      // Detailed Report
      detailedReport: "Detaylı Rapor",
      last7Days: "Son 7 Gün",
      last30Days: "Son 30 Gün",
      daysWithData: "Veri ile Gün Sayısı",
      nutrientTrends: "Besin Değeri Trendleri",
      calorie: "Kalori",
      onTarget: "✓ Hedefte",
      close: "~ Yakın",
      high: "↑ Fazla",
      low: "↓ Az",
      average: "Ortalama",
      target: "Hedef",
      recommendations: "💡 Öneriler",
      tryReducing: "alımını azaltmayı deneyin",
      tryIncreasing: "alımını artırmayı deneyin",
      allOnTarget: "🎉 Harika! Tüm hedeflerinizdesiniz!",
      
      // Charts
      calorieTracking: "Kalori Takibi",
      macroDistribution: "Makro Besin Dağılımı",
      weightTracking: "Kilo Takibi",
      sunday: "Paz",
      monday: "Pzt",
      tuesday: "Sal",
      wednesday: "Çar",
      thursday: "Per",
      friday: "Cum",
      saturday: "Cmt",
      
      // Macros
      carbs: "Karbonhidrat",
      proteinTarget: "Protein Hedefi",
      carbsTarget: "Karbonhidrat Hedefi",
      fatTarget: "Yağ Hedefi",
      
      // Weight Tracking
      current: "Güncel",
      change: "Değişim",
      weeklyAvg: "Haftalık Ort.",
      remaining: "kaldı",
      showGoalLine: "Hedef çizgisini göster",
      open: "Açık",
      closed: "Kapalı",
      kg: "kg",
      kgWeek: "kg/hafta",
      toGoal: "Hedefe",
      timeRange7d: "7G",
      timeRange30d: "30G",
      timeRange90d: "90G",
      timeRangeAll: "Tümü",
      noWeightData: "Henüz Kilo Kaydı Yok",
      noWeightDataDesc: "Kilo takibine başlamak için Profil sayfasından ilk kilonu kaydet! İlerlemenizi burada görüntüleyebileceksiniz.",
      trackRegularly: "Düzenli kayıt yaparak ilerlemenizi takip edin",
      analysis: "Analizler",
      startingWeight: "Başlangıç kilonuz",
      totalChange: "Toplam değişim",
      targetWeight: "Hedef kilonuz",
      dataPoints: "Veri noktası sayısı",
      measurements: "ölçüm",
      goalProgress: "Hedefe İlerleme",
      doingGreat: "Harika gidiyorsun! 🎉",
      keepGoing: "Devam et, sen yaparsın! 💪",
      goodBalance: "İyi bir denge! 👍",
      youLost: "kg verdin!",
      focusOnGoal: "Hedefine odaklan ve devam et!",
      maintainingWeight: "Kilonu koruyorsun, süper!",
    },
    
    // More Page
    more: {
      title: "Daha Fazla",
      description: "Tarifler, geçmiş ve özel gıdalar",
      tipsGuide: "İpuçları & Rehber",
      tipsGuideDesc: "Sağlık, beslenme ve diet ipuçları",
      history: "Geçmiş",
      historyDesc: "Yemek geçmişi",
      customFood: "Özel Gıda",
      customFoodDesc: "Gıda ekle",
      addCustomFood: "Özel Gıda Ekle",
      addCustomFoodDesc: "Kendi gıdanızı oluşturun (100g başına değerler)",
      englishName: "İngilizce Ad",
      turkishName: "Türkçe Ad",
      category: "Kategori",
      caloriesKcal: "Kalori (kcal)",
      proteinG: "Protein (g)",
      carbsG: "Karbonhidrat (g)",
      fatG: "Yağ (g)",
      fiberG: "Lif (g)",
      noteAllValues100g: "Not: Tüm değerler 100 gram için girilmelidir.",
      enterFoodNames: "Lütfen gıda adlarını girin.",
      nutritionNegative: "Besin değerleri negatif olamaz.",
      foodAddError: "Gıda eklenirken bir hata oluştu.",
      measurements: "Ölçümler",
      measurementsDesc: "Vücut ölçüleri",
      progress: "İlerleme",
      progressDesc: "Fotoğraflarım",
      favorites: "Favoriler",
      favoritesDesc: "Favori gıdalar",
      mood: "Ruh Hali",
      moodDesc: "Wellness takibi",
      habits: "Alışkanlıklar",
      habitsDesc: "Günlük hedefler",
      settings: "Ayarlar",
      settingsDesc: "Hesap ve daha fazla",
      myRecipes: "Tariflerim",
      myRecipesDesc: "Kendi tariflerini oluştur ve kaydet",
      mealHistory: "Yemek Geçmişi",
      mealHistoryDesc: "Geçmiş öğünlerini görüntüle",
      weightTracking: "Kilo Takibi",
      weightTrackingDesc: "Kilonu kaydet ve ilerlemeni izle",
      mealPhotos: "Yemek Fotoğrafları",
      mealPhotosDesc: "Yemek fotoğraflarını görüntüle",
      reminders: "Hatırlatıcılar",
      remindersDesc: "Öğün hatırlatıcılarını yönet",
      calculators: "Sağlık Hesaplayıcıları",
      calculatorsDesc: "BMI, BMR, TDEE hesapla",
      fasting: "Aralıklı Oruç",
      fastingDesc: "16:8, 18:6 ve diğer protokoller",
      mealPlanner: "Yemek Planlayıcı",
      mealPlannerDesc: "Haftalık plan ve alışveriş listesi",
      nutrition: "Detaylı Besin Değerleri",
      nutritionDesc: "Vitaminler, mineraller ve daha fazlası",
      theme: "Tema Ayarları",
      themeDesc: "Açık, koyu veya sistem teması",
      export: "Veri Dışa Aktarma",
      exportDesc: "CSV, JSON veya PDF olarak indir",
      bodyMeasurements: "Vücut Ölçümleri",
      bodyMeasurementsDesc: "Bel, kalça, kol ve bacak ölçüleri",
      progressPhotos: "İlerleme Fotoğrafları",
      progressPhotosDesc: "Öncesi/sonrası karşılaştırma",
      favoriteFoods: "Favori Yiyecekler",
      favoriteFoodsDesc: "Hızlı erişim için favori gıdalar",
      
      // History
      noRecords: "Henüz kayıt yok",
      noRecordsDesc: "Bu tarih için henüz yemek kaydı bulunmuyor.",
      portion: "porsiyon",
      deleteConfirm: "Bu yemek kaydını silmek istediğinizden emin misiniz?",
      deleteError: "Yemek silinirken bir hata oluştu.",
      
      // Tips Section
      healthyNutrition: "Sağlıklı Beslenme İpuçları",
      tip1: "Her gün en az 8 bardak su için",
      tip2: "Renkli sebze ve meyveler tüketin",
      tip3: "Protein alımınıza özen gösterin",
      tip4: "İşlenmiş gıdalardan uzak durun",
      tip5: "Düzenli öğün saatleri belirleyin",
      
      weightLossStrategies: "Kilo Verme Stratejileri",
      strategy1: "Kalori açığı oluşturun (300-500 kcal)",
      strategy2: "Haftada 0.5-1 kg hedefleyin",
      strategy3: "Düzenli egzersiz yapın",
      strategy4: "Uyku düzeninize dikkat edin",
      strategy5: "Stresi yönetin",
      
      metabolismBoost: "Metabolizma Hızlandırma",
      metabolism1: "Sabah kahvaltısını atlamayın",
      metabolism2: "Baharat ve baharatlar kullanın",
      metabolism3: "Yeşil çay için",
      metabolism4: "Yüksek protein diyeti uygulayın",
      metabolism5: "Ağırlık antrenmanı yapın",
      
      healthySnacks: "Sağlıklı Atıştırmalıklar",
      snack1: "Çiğ badem ve ceviz",
      snack2: "Taze meyve ve sebzeler",
      snack3: "Yoğurt ve kefir",
      snack4: "Protein barları",
      snack5: "Humus ve sebze çubukları",
    },
    
    // Mood Tracker
    mood: {
      title: "Ruh Hali Takibi",
      subtitle: "Bugün nasıl hissediyorsun?",
      todayStatus: "Bugünün Durumu",
      yourMood: "Ruh Haliniz",
      veryBad: "Çok Kötü",
      bad: "Kötü",
      neutral: "Nötr",
      good: "İyi",
      excellent: "Mükemmel",
      yourEnergy: "Enerji Seviyeniz",
      veryLow: "Çok Düşük",
      low: "Düşük",
      high: "Yüksek",
      veryHigh: "Çok Yüksek",
      notesOptional: "Notlar (İsteğe Bağlı)",
      notesPlaceholder: "Bugün hakkında notlarınızı buraya yazın...",
      last14Days: "Son 14 Gün Trendi",
      mood: "Ruh Hali",
      energy: "Enerji",
      history: "Geçmiş Kayıtlar",
      noEntriesYet: "Henüz kayıt yok. İlk kaydınızı yapmak için yukarıdaki formu doldurun!",
    },
    
    // Favorites
    favorites: {
      title: "Favoriler",
      favorites: "Favoriler",
      newFavorite: "Yeni Favori Ekle",
      searchFood: "Yiyecek Ara",
      noFavoritesYet: "Henüz favori yok",
      addFavoritesDescription: "Sık kullandığınız gıdaları favorilere ekleyerek hızlıca erişebilirsiniz.",
      addFirstFavorite: "İlk Favorini Ekle",
      alreadyInFavorites: "Bu gıda zaten favorilerinizde!",
      confirmRemove: "Bu gıdayı favorilerden kaldırmak istediğinize emin misiniz?",
      foodNotAvailable: "Seçilen gıda bulunamadı.",
    },
    
    // Habits
    habits: {
      title: "Alışkanlık Takipçisi",
      subtitle: "Günlük hedefler ve streak",
      today: "Bugün",
      all: "Tümü",
      longestStreak: "En Uzun Seri",
      total: "Toplam",
      dailyProgress: "Günlük İlerleme",
      congratulations: "🎉 Tebrikler! Bugünkü tüm alışkanlıklarını tamamladın!",
      habitsRemaining: "alışkanlık kaldı",
      addNewHabit: "Yeni Alışkanlık Ekle",
      target: "Hedef",
      day: "Gün",
      week: "Hafta",
      streak: "seri",
      todayLabel: "Bugün",
      complete: "Tamamla",
      noHabitsYet: "Henüz alışkanlık eklemediniz.",
      clickToStart: "Başlamak için yukarıdaki butona tıklayın.",
      daily: "Günlük",
      weekly: "Haftalık",
      dailyStreak: "Günlük Seri",
      successRate: "Başarı Oranı",
      editHabit: "Alışkanlığı Düzenle",
      newHabit: "Yeni Alışkanlık",
      habitName: "Alışkanlık Adı",
      habitPlaceholder: "Örn: Kitap Okuma",
      frequency: "Sıklık",
      targetValue: "Hedef",
      unit: "Birim",
      unitPlaceholder: "kez",
      icon: "İkon",
      color: "Renk",
      update: "Güncelle",
      add: "Ekle",
      deleteHabit: "Sil",
      confirmDelete: "Bu alışkanlığı silmek istediğinizden emin misiniz?",
      times: "kez",
      weekDays: ["P", "P", "S", "Ç", "P", "C", "C"],
    },
    
    // Settings
    settings: {
      title: "Ayarlar",
      description: "Hesap, bildirimler ve tercihler",
      account: "Hesap",
      notifications: "Bildirimler",
      units: "Birimler",
      data: "Veri",
      subscription: "Abonelik",
      about: "Hakkında",
      language: "Dil",
      
      // Account
      accountInfo: "Hesap Bilgileri",
      accountDesc: "Profil ve hedef bilgilerinizi güncelleyin",
      username: "Kullanıcı Adı",
      age: "Yaş",
      weight: "Kilo (kg)",
      height: "Boy (cm)",
      targetWeight: "Hedef Kilo (kg)",
      dailyCalorieGoal: "Günlük Kalori Hedefi",
      saveChanges: "Değişiklikleri Kaydet",
      
      // Toast Messages
      settingsSaved: "Ayarlar kaydedildi!",
      settingsSaveError: "Ayarlar kaydedilemedi: ",
      profileMissing: "Profil bilgileri eksik",
      notificationsSaved: "Bildirim ayarları kaydedildi!",
      notificationsSaveError: "Bildirim ayarları kaydedilemedi",
      unitsSaved: "Birim tercihleri kaydedildi!",
      unitsSaveError: "Birim tercihleri kaydedilemedi",
      localDataCleared: "Yerel veriler temizlendi",
      dataClearError: "Veri temizlenemedi",
      localStorageUnavailable: "Yerel depolama kullanılamıyor",
      confirmClearData: "Tüm yerel verileri temizlemek istediğinizden emin misiniz? Bu işlem geri alınamaz.",
      deleteAccountNotAvailable: "Hesap silme özelliği henüz aktif değil",
      languageChangedTR: "Dil Türkçe olarak değiştirildi",
      languageChangedEN: "Language changed to English",
      languagePreferenceSaved: "Dil tercihiniz cihazınızda kaydedildi.",
      privacyPolicySoon: "Gizlilik politikası yakında eklenecek",
      termsSoon: "Kullanım şartları yakında eklenecek",
      dataExported: "Veriler dışa aktarıldı!",
      
      // Notifications
      mealReminders: "🔔 Öğün Hatırlatıcıları",
      mealRemindersDesc: "Yemek zamanlarında bildirim alın",
      breakfast: "Kahvaltı",
      lunch: "Öğle Yemeği",
      dinner: "Akşam Yemeği",
      waterReminder: "Su İçme Hatırlatıcısı",
      intervalMinutes: "Aralık (dakika)",
      saveNotifications: "Bildirim Ayarlarını Kaydet",
      notificationInfo: "Bildirimlerin çalışması için tarayıcınızda bildirim izni vermeniz gerekebilir.",
      
      // Units
      unitPreferences: "📏 Birim Tercihleri",
      unitPreferencesDesc: "Ölçüm birimlerinizi seçin",
      measurementSystem: "Ölçüm Sistemi",
      metric: "Metrik",
      imperial: "İmparatorluk",
      preview: "Önizleme",
      saveUnits: "Birim Tercihlerini Kaydet",
      
      // Data
      dataManagement: "🗄️ Veri Yönetimi",
      dataManagementDesc: "Verilerinizi yönetin",
      dataExport: "Veri Dışa Aktarma",
      dataExportDesc: "Tüm verilerinizi JSON veya CSV formatında indirebilirsiniz.",
      downloadJSON: "JSON Olarak İndir",
      deleteAccountPermanently: "Hesabı Kalıcı Olarak Sil",
      yesDelete: "Evet, Sil",
      exportData: "Veri Dışa Aktarma",
      exportDataDesc: "Tüm verilerinizi JSON veya CSV formatında indirebilirsiniz.",
      downloadJson: "JSON Olarak İndir",
      clearLocalData: "Yerel Verileri Temizle",
      clearLocalDataDesc: "Tarayıcıda saklanan yerel ayarları ve önbelleği temizler. Supabase verileri korunur.",
      dangerZone: "Tehlikeli Bölge",
      dangerZoneDesc: "Bu işlem geri alınamaz! Tüm verileriniz kalıcı olarak silinecektir.",
      deleteAccount: "Hesabı Kalıcı Olarak Sil",
      confirmDelete: "Emin misiniz? Bu işlem geri alınamaz!",
      
      // Language
      languageSettings: "🌐 Dil Ayarları",
      languageDesc: "Uygulama dilini seçin",
      turkish: "Türkçe",
      english: "English",
      saveLanguage: "Dil Tercihini Kaydet",
      
      // About
      aboutTitle: "ℹ️ Hakkında",
      aboutDesc: "Uygulama bilgileri",
      version: "Versiyon 1.0.0",
      appDescription: "Fitto, sağlıklı yaşam hedeflerinize ulaşmanıza yardımcı olan kapsamlı bir sağlık ve kalori takip uygulamasıdır.",
      features: "Özellikler: Kalori takibi, makro besin yönetimi, egzersiz kaydı, ruh hali takibi, alışkanlık oluşturma ve daha fazlası!",
      contact: "İletişim",
      privacyPolicy: "Gizlilik Politikası",
      termsOfService: "Kullanım Koşulları",
      allRightsReserved: "Tüm hakları saklıdır",
      aboutText: "Fitto, sağlıklı yaşam hedeflerinize ulaşmanıza yardımcı olan kapsamlı bir sağlık ve kalori takip uygulamasıdır.",
      privacy: "🔒 Gizlilik Politikası",
      terms: "📜 Kullanım Şartları",
      madeWith: "Made with ❤️ by Fitto Team",
      copyright: "© 2024 Fitto. Tüm hakları saklıdır.",
    },
    
    // Subscription
    subscription: {
      title: "Abonelik Yönetimi",
      description: "Premium özelliklere erişin ve AI destekli beslenme koçundan yararlanın",
      currentPlan: "Mevcut Planınız",
      endDate: "Bitiş tarihi",
      aiFeatures: "AI Özellikleri",
      aiDescription: "Premium planlarla yapay zeka destekli özelliklerden yararlanın",
      
      // Plans
      free: "Ücretsiz",
      monthly: "Aylık",
      quarterly: "3 Aylık",
      yearly: "Yıllık",
      
      freePeriod: "süresiz",
      monthlyPeriod: "ay",
      quarterlyPeriod: "3 ay",
      yearlyPeriod: "yıl",
      
      mostPopular: "En Popüler",
      active: "Aktif",
      processing: "İşleniyor...",
      currentPlanButton: "Mevcut Plan",
      useFree: "Ücretsiz Kullan",
      upgrade: "Yükselt",
      demoNote: "Not",
      demoDescription: "Bu demo bir uygulamadır. Gerçek ödeme işlemi yapılmamaktadır. İstediğiniz planı seçerek premium özellikleri test edebilirsiniz.",
      alreadyOnPlan: "Zaten bu plandayınız",
      cancelTip: "Ücretsiz plana geçiş için mevcut aboneliğinizi iptal edin",
      upgradeSuccess: "Abonelik başarıyla güncellendi! 🎉",
      upgradeError: "Abonelik güncellenemedi",
      discount15: "%15 İndirimli",
      discount30: "%30 İndirimli",
      save: "Tasarruf",
      save15: "15% Tasarruf",
      save30: "30% Tasarruf",
      
      // Features
      allFreeFeatures: "Tüm ücretsiz özellikler",
      allMonthlyFeatures: "Tüm aylık özellikler",
      calorieTracking: "Kalori ve makro takibi",
      exerciseLog: "Egzersiz kaydı",
      manualFood: "Manuel besin girişi",
      basicReports: "Temel raporlar",
      aiPhotoAnalysis: "AI fotoğraf analizi",
      advancedDatabase: "Gelişmiş besin veritabanı",
      unlimitedRecipes: "Sınırsız tarif",
      detailedAnalytics: "Detaylı analitikler",
      prioritySupport: "Öncelikli destek",
      adFree: "Reklamsız deneyim",
      aiNutritionCoach: "AI beslenme koçu",
      personalizedPlans: "Kişiselleştirilmiş planlar",
      advancedReports: "İleri düzey raporlar",
      earlyAccess: "Erken erişim özellikleri",
      
      // AI Features list
      aiFeature1: "📸 Fotoğraftan otomatik besin tanıma ve kalori hesaplama",
      aiFeature2: "🤖 AI beslenme koçu ile kişiselleştirilmiş öneriler",
      aiFeature3: "📊 Gelişmiş besin analizi ve makro optimizasyonu",
    },
    
    // Connection States
    connection: {
      connecting: "Bağlanıyor...",
      verifying: "Kimlik Doğrulanıyor...",
      pleaseWait: "Lütfen bekleyin",
      connectionError: "Bağlantı Hatası",
      databaseError: "Veritabanına bağlanılamadı",
    },
    
    // Recipes
    recipes: {
      title: "Tarif Ara",
      subtitle: "Binlerce tarif keşfedin",
      searchPlaceholder: "Tarif ara... (tavuk, kebap, çorba, makarna)",
      searching: "Aranıyor...",
      search: "Ara",
      popularSearches: "Popüler aramalar:",
      emptyState: "Tarif aramak için yukarıdaki arama çubuğunu kullanın",
      errorLoadRecipes: "Tarifler yüklenemedi",
      errorNotFound: "Tarif bulunamadı. Farklı bir arama deneyin.",
      errorTimeout: "Arama zaman aşımına uğradı. Lütfen tekrar deneyin.",
      errorGeneral: "Bir hata oluştu. Lütfen tekrar deneyin.",
      errorPleaseEnter: "Lütfen bir tarif adı girin",
      
      // Recipe Detail
      errorLoadDetails: "Tarif detayları yüklenemedi",
      errorNotFoundDetails: "Tarif bulunamadı",
      errorLoadingDetails: "Tarif yüklenirken bir hata oluştu",
      recipeTag: "(Tarif)",
      errorAddingToLog: "Günlüğe eklenirken bir hata oluştu",
      back: "Geri",
      close: "Kapat",
      ingredients: "Malzemeler",
      instructions: "Yapılışı",
      watchOnYoutube: "📺 YouTube'da İzle",
      tags: "Etiketler:",
      added: "Eklendi!",
      adding: "Ekleniyor...",
      addToLog: "Günlüğe Ekle",
      nutritionNote: "Not: TheMealDB besin değeri bilgisi sağlamıyor. Manuel düzenleme gerekebilir.",
      
      // Recipe Manager
      myRecipes: "Tariflerim",
      searchRecipes: "Tarif Ara",
      newRecipe: "Yeni Tarif",
      noRecipesYet: "Henüz tarif yok",
      createYourRecipes: "Kendi tariflerinizi oluşturun ve kaydedin!",
      createFirstRecipe: "İlk Tarifini Oluştur",
      recipe: "Tarif:",
      ingredientsList: "Malzemeler:",
      caloriesPerServing: "kcal/porsiyon",
      protein: "Protein",
      carbs: "Karbonhidrat",
      fat: "Yağ",
      createNewRecipe: "Yeni Tarif Oluştur",
      createNewRecipeDesc: "Kendi tarifini oluştur ve kaydet",
      recipeName: "Tarif Adı",
      recipeNamePlaceholder: "Örn: Izgara Tavuk Salatası",
      servings: "Porsiyon Sayısı",
      prepTime: "Hazırlama (dk)",
      recipeNotes: "Tarif Notları",
      recipeNotesPlaceholder: "Hazırlama talimatları...",
      ingredientsLabel: "Malzemeler",
      grams: "g",
      searchIngredient: "Malzeme ara...",
      cancel: "İptal",
      create: "Oluştur",
      minutes: "dk",
      serving: "porsiyon",
      unknown: "Bilinmeyen",
      errorLoadingRecipes: "Tarif listesi alınırken hata:",
      errorLoadingFoods: "Gıda listesi alınırken hata:",
      errorPleaseEnterName: "Lütfen tarif adı girin ve en az bir malzeme ekleyin.",
      errorCreatingRecipe: "Tarif oluşturulurken hata:",
      errorCreatingRecipeMsg: "Tarif oluşturulurken bir hata oluştu.",
      confirmDelete: "Bu tarifi silmek istediğinizden emin misiniz?",
      errorDeletingRecipe: "Tarif silinirken hata:",
      errorDeletingRecipeMsg: "Tarif silinirken bir hata oluştu.",
      
      // Page
      pageTitle: "Tarif Ara",
      connectionError: "Bağlantı hatası",
      connectionFailed: "Bağlantı kurulamadı. Lütfen tekrar deneyin.",
      reload: "Yenile",
      loading: "Yükleniyor...",
      howToUse: "Nasıl Kullanılır?",
      howToUseStep1: "• Arama kutusuna Türkçe veya İngilizce tarif adı yazın",
      howToUseStep2: "• Popüler aramalardan birini seçerek hızlıca başlayın",
      howToUseStep3: "• Tarifin detaylarını görmek için kartına tıklayın",
      howToUseStep4: "• Malzemeler, yapılışı ve besin değerleri görüntülenecek",
      securityNote: "Tüm aramalarınız güvenli API rotalarından geçer. Kişisel verileriniz korunur ve üçüncü taraflarla paylaşılmaz. Tarifler TheMealDB API'sinden sağlanır.",
    },
    
    // Water Tracking
    water: {
      title: "Su Takibi",
      tip: "Günlük hedefinize ulaşmak için bardaklara tıklayın!",
      glasses: "Bardak",
      goalCompleted: "Harika! Günlük hedefinizi tamamladınız!",
      clickToStart: "Su içmeye başlamak için bir bardağa tıklayın!",
      greatStart: "Harika başlangıç! Devam edin!",
      halfway: "Yarı yoldasınız! Hedefinize çok yaklaştınız!",
    },
    
    // AI Coach
    aiCoach: {
      title: "AI Beslenme Koçu",
      subtitle: "24/7 kişisel beslenme asistanınız",
      startTrial: "3 Gün Ücretsiz Dene",
      startTrialDesc: "9 mesaj hakkı, günlük 3 mesaj limiti",
      watchAd: "Reklam İzle",
      watchAdDesc: "Her reklam için 3 mesaj hakkı kazan",
      upgradePremium: "Premium'a Yükselt",
      upgradePremiumDesc: "Sınırsız AI Coach erişimi",
      trialActive: "Deneme Aktif",
      daysLeft: "gün kaldı",
      messagesLeft: "mesaj kaldı",
      dailyLimit: "Günlük limit",
      adCredits: "Reklam Kredisi",
      quickQuestions: "Hızlı Sorular",
      whatToEat: "Ne yesem?",
      calorieHelp: "Kalori yardımı",
      proteinTip: "Protein önerisi",
      motivate: "Motivasyon",
      typeMessage: "Mesajını yaz...",
      send: "Gönder",
      noAccess: "AI Coach erişiminiz yok",
      trialExpired: "Deneme süresi doldu",
      chooseOption: "Erişim için bir seçenek seçin",
      aiThinking: "AI düşünüyor...",
      errorSending: "Mesaj gönderilemedi",
      tryAgain: "Tekrar deneyin",
      close: "Kapat",
    },
  },
  
  en: {
    // Common
    common: {
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      back: 'Back',
      next: 'Continue',
      finish: 'Complete',
      skip: 'Skip',
      yes: 'Yes',
      no: 'No',
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
      add: 'Add',
      search: 'Search',
      close: 'Close',
      select: 'Select',
    },
    
    // Welcome Screen
    welcome: {
      title: "Welcome to Fitto",
      description: "We're with you on your healthy living journey. Calorie, macro, and exercise tracking is now super easy!",
      slide1Title: "Welcome to Fitto",
      slide1Desc: "We're with you on your healthy living journey. Calorie, macro, and exercise tracking is now super easy!",
      slide2Title: "Set Your Goals",
      slide2Desc: "Whether you want to lose weight, build muscle, or stay healthy - create a personalized plan for your goals.",
      slide3Title: "Track Your Progress",
      slide3Desc: "Easily track daily calories, macronutrients, water intake, and more.",
      slide4Title: "See Results",
      slide4Desc: "Analyze your progress with detailed reports and charts, keep your motivation high!",
      getStarted: "Let's Start",
      continue: "Continue",
    },
    
    // Onboarding
    onboarding: {
      createProfile: "Create Your Profile ✨",
      step1Desc: "Enter your personal information",
      step2Desc: "Set your goals",
      username: "Username",
      usernamePlaceholder: "Your Name",
      age: "Age",
      agePlaceholder: "e.g., 25",
      weight: "Weight (kg)",
      weightPlaceholder: "e.g., 70",
      height: "Height (cm)",
      heightPlaceholder: "e.g., 175",
      gender: "Gender",
      genderSelect: "Select",
      male: "Male",
      female: "Female",
      other: "Other",
      activityLevel: "Activity Level",
      sedentary: "Sedentary (Office job)",
      lightlyActive: "Lightly Active (Light exercise 1-3 days/week)",
      moderatelyActive: "Moderately Active (Moderate exercise 3-5 days/week)",
      veryActive: "Very Active (Intense exercise 6-7 days/week)",
      extraActive: "Extra Active (Heavy physical work)",
      goal: "Goal",
      lose: "Lose Weight",
      maintain: "Maintain Weight",
      gain: "Gain Weight",
      buildMuscle: "Build Muscle",
      targetWeight: "Target Weight (kg)",
      back: "← Back",
      complete: "Complete ✓",
    },
    
    // Bottom Navigation
    nav: {
      home: "Home",
      stats: "Stats",
      recipes: "Recipes",
      more: "More",
      profile: "Profile",
    },
    
    // Profile
    profile: {
      title: "My Profile",
      description: "Your personal information and goals",
      currentWeight: "Current Weight (kg)",
      height: "Height (cm)",
      bmi: "BMI",
      targetWeight: "Target Weight (kg)",
      myGoals: "My Goals",
      activityLevel: "Activity Level",
      goalType: "Goal Type",
      dailyCalorie: "Daily Calorie",
      macroGoals: "My Daily Macro Goals",
      protein: "Protein",
      carbs: "Carbs",
      fat: "Fat",
      age: "years old",
      underweight: "Underweight",
      normal: "Normal",
      overweight: "Overweight",
      obese: "Obese",
    },
    
    // Meal Tracking
    meals: {
      title: "Meal Tracking",
      description: "Log your daily meals",
      dailyCalorie: "Daily Calorie",
      yourGoal: "Your goal for today",
      remaining: "remaining",
      goalReached: "🎉 You've reached your daily goal!",
      completed: "completed",
      dailyMeals: "Daily Meals",
      breakfast: "Breakfast",
      lunch: "Lunch",
      dinner: "Dinner",
      snack: "Snack",
      snackAlt: "Snack",
      notAdded: "Not added yet",
      foods: "foods",
      motivationStart: "🍽️ Start adding your first meal!",
      motivationGood: "💪 You're doing great! Keep going!",
      motivationClose: "🔥 You're very close to your goal!",
      motivationComplete: "🎉 You've reached your daily goal!",
      balancedDiet: "Balanced nutrition is the foundation of healthy living",
      addMeal: "Add Meal",
      addMealDesc: "Add food to your meal today",
      mealType: "Meal",
      searchFood: "Search Food",
      searchPlaceholder: "e.g., chicken, cheese, apple...",
      recentFoods: "Recent Foods",
      foundResults: "Found Results",
      noResults: "No results found for",
      noResultsHelp: "You can use the custom food option",
      portion: "Portion (grams)",
      nutritionValues: "Nutrition Values",
      calories: "Calories",
      addPhoto: "📸 Add Photo",
      customFood: "Custom Food",
      barcodeScan: "Scan Barcode",
      minChars: "Enter at least 3 characters...",
    },
    
    // Exercise Tracking
    exercise: {
      title: "Exercise Tracking",
      description: "Stay active and healthy! 💪",
      add: "Add",
      today: "Today",
      stats: "Statistics",
      history: "History",
      todaySummary: "Today's Summary",
      caloriesBurned: "Calories Burned",
      minutes: "Minutes",
      weeklyGoal: "Weekly Goal",
      weeklyGoalDesc: "150 minutes of exercise per week is recommended 🎯",
      todayExercises: "Today's Exercises",
      noExerciseToday: "You haven't added any exercise today.",
      letsGetMoving: "Let's get moving! 🚀",
      addFirstExercise: "Add Your First Exercise",
      favoriteExercises: "My Favorite Exercises",
      thisWeek: "This Week",
      thisMonth: "This Month",
      all: "All",
      totalCalories: "Total Calories",
      totalMinutes: "Total Minutes",
      exerciseCount: "Exercise Count",
      avgPerSession: "Avg Calories/Session",
      mostFrequent: "Most Frequent Exercise",
      last7Days: "Last 7 Days",
      noExerciseHistory: "You don't have any exercise history yet.",
      startFirst: "Click the button above to start your first exercise! 💪",
      tip: "💡 Tip",
      tipText: "By exercising regularly, you can speed up your metabolism and burn more calories!",
      addExercise: "Add Exercise",
      addExerciseDesc: "Log your activity today",
      commonExercises: "Common Exercises",
      customExercise: "Custom Exercise",
      customExercisePlaceholder: "Write your own exercise name...",
      duration: "Duration (minutes)",
      caloriesBurnedInput: "Calories Burned (kcal)",
      walking: "Walking",
      running: "Running",
      cycling: "Cycling",
      swimming: "Swimming",
      weightTraining: "Weight Training",
      yoga: "Yoga",
      pilates: "Pilates",
      dancing: "Dancing",
      exercises: "exercises",
    },
    
    // Stats Page
    stats: {
      title: "My Statistics",
      description: "Track your progress and reach your goals!",
      consecutiveDays: "Consecutive Days",
      mealLogs: "Meal Logs",
      avgCalories: "Avg Calories",
      exercises: "Exercises",
      weekly: "Weekly",
      monthly: "Monthly",
      
      // Achievements
      achievements: "Achievements",
      firstStep: "First Step",
      firstStepDesc: "Log your first meal",
      determined: "Determined",
      determinedDesc: "Log for 7 consecutive days",
      disciplined: "Disciplined",
      disciplinedDesc: "Log for 30 consecutive days",
      follower: "Follower",
      followerDesc: "Log 50 meals",
      expert: "Expert",
      expertDesc: "Log 100 meals",
      active: "Active",
      activeDesc: "Log 10 exercises",
      athlete: "Athlete",
      athleteDesc: "Log 50 exercises",
      superHero: "Super Hero",
      superHeroDesc: "100 meals + 50 exercises",
      allUnlocked: "🎉 All Achievements Unlocked!",
      greatJob: "You did an amazing job!",
      
      // Detailed Report
      detailedReport: "Detailed Report",
      last7Days: "Last 7 Days",
      last30Days: "Last 30 Days",
      daysWithData: "Days with Data",
      nutrientTrends: "Nutrient Trends",
      calorie: "Calorie",
      onTarget: "✓ On Target",
      close: "~ Close",
      high: "↑ High",
      low: "↓ Low",
      average: "Average",
      target: "Target",
      recommendations: "💡 Recommendations",
      tryReducing: "try reducing intake",
      tryIncreasing: "try increasing intake",
      allOnTarget: "🎉 Great! You're hitting all your targets!",
      
      // Charts
      calorieTracking: "Calorie Tracking",
      macroDistribution: "Macro Distribution",
      weightTracking: "Weight Tracking",
      sunday: "Sun",
      monday: "Mon",
      tuesday: "Tue",
      wednesday: "Wed",
      thursday: "Thu",
      friday: "Fri",
      saturday: "Sat",
      
      // Macros
      carbs: "Carbs",
      proteinTarget: "Protein Target",
      carbsTarget: "Carbs Target",
      fatTarget: "Fat Target",
      
      // Weight Tracking
      current: "Current",
      change: "Change",
      weeklyAvg: "Weekly Avg",
      remaining: "remaining",
      showGoalLine: "Show goal line",
      open: "On",
      closed: "Off",
      kg: "kg",
      kgWeek: "kg/week",
      toGoal: "To Goal",
      timeRange7d: "7D",
      timeRange30d: "30D",
      timeRange90d: "90D",
      timeRangeAll: "All",
      noWeightData: "No Weight Data Yet",
      noWeightDataDesc: "Start tracking your weight from the Profile page! You'll be able to view your progress here.",
      trackRegularly: "Track regularly to monitor your progress",
      analysis: "Analysis",
      startingWeight: "Your starting weight",
      totalChange: "Total change",
      targetWeight: "Your target weight",
      dataPoints: "Number of data points",
      measurements: "measurements",
      goalProgress: "Goal Progress",
      doingGreat: "You're doing great! 🎉",
      keepGoing: "Keep going, you can do it! 💪",
      goodBalance: "Good balance! 👍",
      youLost: "kg lost!",
      focusOnGoal: "Focus on your goal and keep going!",
      maintainingWeight: "Maintaining your weight, great!",
    },
    
    // More Page
    more: {
      title: "More",
      description: "Recipes, history, and custom foods",
      tipsGuide: "Tips & Guide",
      tipsGuideDesc: "Health, nutrition, and diet tips",
      history: "History",
      historyDesc: "Meal history",
      customFood: "Custom Food",
      customFoodDesc: "Add food",
      addCustomFood: "Add Custom Food",
      addCustomFoodDesc: "Create your own food (values per 100g)",
      englishName: "English Name",
      turkishName: "Turkish Name",
      category: "Category",
      caloriesKcal: "Calories (kcal)",
      proteinG: "Protein (g)",
      carbsG: "Carbs (g)",
      fatG: "Fat (g)",
      fiberG: "Fiber (g)",
      noteAllValues100g: "Note: All values should be entered per 100 grams.",
      enterFoodNames: "Please enter food names.",
      nutritionNegative: "Nutrition values cannot be negative.",
      foodAddError: "An error occurred while adding food.",
      measurements: "Measurements",
      measurementsDesc: "Body measurements",
      progress: "Progress",
      progressDesc: "My photos",
      favorites: "Favorites",
      favoritesDesc: "Favorite foods",
      mood: "Mood",
      moodDesc: "Wellness tracking",
      habits: "Habits",
      habitsDesc: "Daily goals",
      settings: "Settings",
      settingsDesc: "Account and more",
      myRecipes: "My Recipes",
      myRecipesDesc: "Create and save your own recipes",
      mealHistory: "Meal History",
      mealHistoryDesc: "View past meals",
      weightTracking: "Weight Tracking",
      weightTrackingDesc: "Log your weight and track progress",
      mealPhotos: "Meal Photos",
      mealPhotosDesc: "View meal photos",
      reminders: "Reminders",
      remindersDesc: "Manage meal reminders",
      calculators: "Health Calculators",
      calculatorsDesc: "Calculate BMI, BMR, TDEE",
      fasting: "Intermittent Fasting",
      fastingDesc: "16:8, 18:6 and other protocols",
      mealPlanner: "Meal Planner",
      mealPlannerDesc: "Weekly plan and shopping list",
      nutrition: "Detailed Nutrition",
      nutritionDesc: "Vitamins, minerals, and more",
      theme: "Theme Settings",
      themeDesc: "Light, dark, or system theme",
      export: "Data Export",
      exportDesc: "Download as CSV, JSON, or PDF",
      bodyMeasurements: "Body Measurements",
      bodyMeasurementsDesc: "Waist, hip, arm, and leg measurements",
      progressPhotos: "Progress Photos",
      progressPhotosDesc: "Before/after comparison",
      favoriteFoods: "Favorite Foods",
      favoriteFoodsDesc: "Quick access to favorite foods",
      
      // History
      noRecords: "No Records Yet",
      noRecordsDesc: "No meal records found for this date.",
      portion: "portion",
      deleteConfirm: "Are you sure you want to delete this meal record?",
      deleteError: "An error occurred while deleting the meal.",
      
      // Tips Section
      healthyNutrition: "Healthy Nutrition Tips",
      tip1: "Drink at least 8 glasses of water daily",
      tip2: "Consume colorful vegetables and fruits",
      tip3: "Pay attention to your protein intake",
      tip4: "Avoid processed foods",
      tip5: "Set regular meal times",
      
      weightLossStrategies: "Weight Loss Strategies",
      strategy1: "Create a calorie deficit (300-500 kcal)",
      strategy2: "Aim for 0.5-1 kg per week",
      strategy3: "Exercise regularly",
      strategy4: "Pay attention to your sleep schedule",
      strategy5: "Manage stress",
      
      metabolismBoost: "Boost Your Metabolism",
      metabolism1: "Don't skip breakfast",
      metabolism2: "Use spices and seasonings",
      metabolism3: "Drink green tea",
      metabolism4: "Follow a high-protein diet",
      metabolism5: "Do weight training",
      
      healthySnacks: "Healthy Snacks",
      snack1: "Raw almonds and walnuts",
      snack2: "Fresh fruits and vegetables",
      snack3: "Yogurt and kefir",
      snack4: "Protein bars",
      snack5: "Hummus and vegetable sticks",
    },
    
    // Mood Tracker
    mood: {
      title: "Mood Tracking",
      subtitle: "How are you feeling today?",
      todayStatus: "Today's Status",
      yourMood: "Your Mood",
      veryBad: "Very Bad",
      bad: "Bad",
      neutral: "Neutral",
      good: "Good",
      excellent: "Excellent",
      yourEnergy: "Your Energy Level",
      veryLow: "Very Low",
      low: "Low",
      high: "High",
      veryHigh: "Very High",
      notesOptional: "Notes (Optional)",
      notesPlaceholder: "Write your notes about today here...",
      last14Days: "Last 14 Days Trend",
      mood: "Mood",
      energy: "Energy",
      history: "History Records",
      noEntriesYet: "No entries yet. Fill out the form above to create your first record!",
    },
    
    // Favorites
    favorites: {
      title: "Favorites",
      favorites: "Favorites",
      newFavorite: "Add New Favorite",
      searchFood: "Search Food",
      noFavoritesYet: "No favorites yet",
      addFavoritesDescription: "Add your frequently used foods to favorites for quick access.",
      addFirstFavorite: "Add Your First Favorite",
      alreadyInFavorites: "This food is already in your favorites!",
      confirmRemove: "Are you sure you want to remove this food from favorites?",
      foodNotAvailable: "The selected food was not found.",
    },
    
    // Habits
    habits: {
      title: "Habit Tracker",
      subtitle: "Daily goals and streaks",
      today: "Today",
      all: "All",
      longestStreak: "Longest Streak",
      total: "Total",
      dailyProgress: "Daily Progress",
      congratulations: "🎉 Congratulations! You completed all your habits today!",
      habitsRemaining: "habits remaining",
      addNewHabit: "Add New Habit",
      target: "Target",
      day: "Day",
      week: "Week",
      streak: "streak",
      todayLabel: "Today",
      complete: "Complete",
      noHabitsYet: "You haven't added any habits yet.",
      clickToStart: "Click the button above to get started.",
      daily: "Daily",
      weekly: "Weekly",
      dailyStreak: "Daily Streak",
      successRate: "Success Rate",
      editHabit: "Edit Habit",
      newHabit: "New Habit",
      habitName: "Habit Name",
      habitPlaceholder: "e.g., Read Books",
      frequency: "Frequency",
      targetValue: "Target",
      unit: "Unit",
      unitPlaceholder: "times",
      icon: "Icon",
      color: "Color",
      update: "Update",
      add: "Add",
      deleteHabit: "Delete",
      confirmDelete: "Are you sure you want to delete this habit?",
      times: "times",
      weekDays: ["M", "T", "W", "T", "F", "S", "S"],
    },
    
    // Settings
    settings: {
      title: "Settings",
      description: "Account, notifications, and preferences",
      account: "Account",
      notifications: "Notifications",
      units: "Units",
      data: "Data",
      subscription: "Subscription",
      about: "About",
      language: "Language",
      
      // Account
      accountInfo: "Account Information",
      accountDesc: "Update your profile and goal information",
      username: "Username",
      age: "Age",
      weight: "Weight (kg)",
      height: "Height (cm)",
      targetWeight: "Target Weight (kg)",
      dailyCalorieGoal: "Daily Calorie Goal",
      saveChanges: "Save Changes",
      
      // Notifications
      mealReminders: "🔔 Meal Reminders",
      mealRemindersDesc: "Get notifications at meal times",
      breakfast: "Breakfast",
      lunch: "Lunch",
      dinner: "Dinner",
      waterReminder: "Water Reminder",
      intervalMinutes: "Interval (minutes)",
      saveNotifications: "Save Notification Settings",
      notificationInfo: "You may need to grant notification permission in your browser for notifications to work.",
      
      // Units
      unitPreferences: "📏 Unit Preferences",
      unitPreferencesDesc: "Choose your measurement units",
      measurementSystem: "Measurement System",
      metric: "Metric",
      imperial: "Imperial",
      preview: "Preview",
      saveUnits: "Save Unit Preferences",
      
      // Data
      dataManagement: "🗄️ Data Management",
      dataManagementDesc: "Manage your data",
      dataExport: "Data Export",
      dataExportDesc: "You can download all your data in JSON or CSV format.",
      downloadJSON: "Download as JSON",
      deleteAccountPermanently: "Permanently Delete Account",
      yesDelete: "Yes, Delete",
      exportData: "Export Data",
      exportDataDesc: "You can download all your data in JSON or CSV format.",
      downloadJson: "Download as JSON",
      clearLocalData: "Clear Local Data",
      clearLocalDataDesc: "Clears local settings and cache stored in the browser. Supabase data is preserved.",
      dangerZone: "Danger Zone",
      dangerZoneDesc: "This action cannot be undone! All your data will be permanently deleted.",
      deleteAccount: "Permanently Delete Account",
      confirmDelete: "Are you sure? This action cannot be undone!",
      
      // Language
      languageSettings: "🌐 Language Settings",
      languageDesc: "Select application language",
      turkish: "Türkçe",
      english: "English",
      saveLanguage: "Save Language Preference",
      
      // About
      aboutTitle: "ℹ️ About",
      aboutDesc: "Application information",
      version: "Version 1.0.0",
      appDescription: "Fitto is a comprehensive health and calorie tracking application that helps you achieve your healthy living goals.",
      features: "Features: Calorie tracking, macronutrient management, exercise logging, mood tracking, habit formation, and more!",
      contact: "Contact",
      privacyPolicy: "Privacy Policy",
      termsOfService: "Terms of Service",
      allRightsReserved: "All rights reserved",
      aboutText: "Fitto is a comprehensive health and calorie tracking application that helps you achieve your healthy living goals.",
      privacy: "🔒 Privacy Policy",
      terms: "📜 Terms of Service",
      madeWith: "Made with ❤️ by Fitto Team",
      copyright: "© 2024 Fitto. All rights reserved.",
    },
    
    // Subscription
    subscription: {
      title: "Subscription Management",
      description: "Access premium features and benefit from AI-powered nutrition coaching",
      currentPlan: "Your Current Plan",
      endDate: "End date",
      aiFeatures: "AI Features",
      aiDescription: "Take advantage of AI-powered features with premium plans",
      
      // Plans
      free: "Free",
      monthly: "Monthly",
      quarterly: "3 Months",
      yearly: "Yearly",
      
      freePeriod: "forever",
      monthlyPeriod: "month",
      quarterlyPeriod: "3 months",
      yearlyPeriod: "year",
      
      mostPopular: "Most Popular",
      active: "Active",
      processing: "Processing...",
      currentPlanButton: "Current Plan",
      useFree: "Use Free",
      upgrade: "Upgrade",
      demoNote: "Note",
      demoDescription: "This is a demo application. No actual payment is processed. You can select any plan to test premium features.",
      alreadyOnPlan: "You are already on this plan",
      cancelTip: "To switch to free plan, cancel your current subscription",
      upgradeSuccess: "Subscription updated successfully! 🎉",
      upgradeError: "Failed to update subscription",
      discount15: "15% Off",
      discount30: "30% Off",
      save: "Savings",
      save15: "Save 15%",
      save30: "Save 30%",
      
      // Features
      allFreeFeatures: "All free features",
      allMonthlyFeatures: "All monthly features",
      calorieTracking: "Calorie and macro tracking",
      exerciseLog: "Exercise logging",
      manualFood: "Manual food entry",
      basicReports: "Basic reports",
      aiPhotoAnalysis: "AI photo analysis",
      advancedDatabase: "Advanced food database",
      unlimitedRecipes: "Unlimited recipes",
      detailedAnalytics: "Detailed analytics",
      prioritySupport: "Priority support",
      adFree: "Ad-free experience",
      aiNutritionCoach: "AI nutrition coach",
      personalizedPlans: "Personalized plans",
      advancedReports: "Advanced reports",
      earlyAccess: "Early access features",
      
      // AI Features list
      aiFeature1: "📸 Automatic food recognition and calorie calculation from photos",
      aiFeature2: "🤖 Personalized recommendations with AI nutrition coach",
      aiFeature3: "📊 Advanced nutrition analysis and macro optimization",
    },
    
    // Connection States
    connection: {
      connecting: "Connecting...",
      verifying: "Verifying Identity...",
      pleaseWait: "Please wait",
      connectionError: "Connection Error",
      databaseError: "Unable to connect to database",
    },
    
    // Recipes
    recipes: {
      title: "Search Recipes",
      subtitle: "Discover thousands of recipes",
      searchPlaceholder: "Search recipes... (chicken, kebab, soup, pasta)",
      searching: "Searching...",
      search: "Search",
      popularSearches: "Popular searches:",
      emptyState: "Use the search bar above to find recipes",
      errorLoadRecipes: "Failed to load recipes",
      errorNotFound: "No recipes found. Try a different search.",
      errorTimeout: "Search timed out. Please try again.",
      errorGeneral: "An error occurred. Please try again.",
      errorPleaseEnter: "Please enter a recipe name",
      
      // Recipe Detail
      errorLoadDetails: "Failed to load recipe details",
      errorNotFoundDetails: "Recipe not found",
      errorLoadingDetails: "An error occurred while loading the recipe",
      recipeTag: "(Recipe)",
      errorAddingToLog: "An error occurred while adding to log",
      back: "Back",
      close: "Close",
      ingredients: "Ingredients",
      instructions: "Instructions",
      watchOnYoutube: "📺 Watch on YouTube",
      tags: "Tags:",
      added: "Added!",
      adding: "Adding...",
      addToLog: "Add to Log",
      nutritionNote: "Note: TheMealDB does not provide nutritional information. Manual editing may be required.",
      
      // Recipe Manager
      myRecipes: "My Recipes",
      searchRecipes: "Search Recipes",
      newRecipe: "New Recipe",
      noRecipesYet: "No recipes yet",
      createYourRecipes: "Create and save your own recipes!",
      createFirstRecipe: "Create Your First Recipe",
      recipe: "Recipe:",
      ingredientsList: "Ingredients:",
      caloriesPerServing: "kcal/serving",
      protein: "Protein",
      carbs: "Carbs",
      fat: "Fat",
      createNewRecipe: "Create New Recipe",
      createNewRecipeDesc: "Create and save your own recipe",
      recipeName: "Recipe Name",
      recipeNamePlaceholder: "E.g: Grilled Chicken Salad",
      servings: "Servings",
      prepTime: "Prep Time (min)",
      recipeNotes: "Recipe Notes",
      recipeNotesPlaceholder: "Preparation instructions...",
      ingredientsLabel: "Ingredients",
      grams: "g",
      searchIngredient: "Search ingredient...",
      cancel: "Cancel",
      create: "Create",
      minutes: "min",
      serving: "serving",
      unknown: "Unknown",
      errorLoadingRecipes: "Error loading recipe list:",
      errorLoadingFoods: "Error loading food list:",
      errorPleaseEnterName: "Please enter a recipe name and add at least one ingredient.",
      errorCreatingRecipe: "Error creating recipe:",
      errorCreatingRecipeMsg: "An error occurred while creating the recipe.",
      confirmDelete: "Are you sure you want to delete this recipe?",
      errorDeletingRecipe: "Error deleting recipe:",
      errorDeletingRecipeMsg: "An error occurred while deleting the recipe.",
      
      // Page
      pageTitle: "Search Recipes",
      connectionError: "Connection error",
      connectionFailed: "Connection failed. Please try again.",
      reload: "Reload",
      loading: "Loading...",
      howToUse: "How to Use?",
      howToUseStep1: "• Type recipe name in Turkish or English in the search box",
      howToUseStep2: "• Select one of the popular searches to get started quickly",
      howToUseStep3: "• Click on the card to see recipe details",
      howToUseStep4: "• Ingredients, instructions, and nutrition values will be displayed",
      securityNote: "All your searches go through secure API routes. Your personal data is protected and not shared with third parties. Recipes are provided by TheMealDB API.",
    },
    
    // Water Tracking
    water: {
      title: "Water Tracking",
      tip: "Click on glasses to reach your daily goal!",
      glasses: "Glasses",
      goalCompleted: "Great! You completed your daily goal!",
      clickToStart: "Click on a glass to start drinking water!",
      greatStart: "Great start! Keep going!",
      halfway: "Halfway there! You're very close to your goal!",
    },
    
    // AI Coach
    aiCoach: {
      title: "AI Nutrition Coach",
      subtitle: "Your 24/7 personal nutrition assistant",
      startTrial: "Try 3 Days Free",
      startTrialDesc: "9 message credits, 3 messages daily limit",
      watchAd: "Watch Ad",
      watchAdDesc: "Earn 3 message credits per ad",
      upgradePremium: "Upgrade to Premium",
      upgradePremiumDesc: "Unlimited AI Coach access",
      trialActive: "Trial Active",
      daysLeft: "days left",
      messagesLeft: "messages left",
      dailyLimit: "Daily limit",
      adCredits: "Ad Credits",
      quickQuestions: "Quick Questions",
      whatToEat: "What should I eat?",
      calorieHelp: "Calorie help",
      proteinTip: "Protein suggestion",
      motivate: "Motivation",
      typeMessage: "Type your message...",
      send: "Send",
      noAccess: "No AI Coach access",
      trialExpired: "Trial expired",
      chooseOption: "Choose an option for access",
      aiThinking: "AI thinking...",
      errorSending: "Failed to send message",
      tryAgain: "Try again",
      close: "Close",
    },
  },
};
